/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.mafer.campominado;

import java.awt.GridLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author fefe
 */
public class MenuInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicial.class.getName());

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        String[] opcoesDificuldade = {"Fácil: 9x9, 10 minas ", "Médio: 16x16, 40 minas", "Avançado: 30x16, 99 minas"};
        ComboBoxDificuldade.setModel(new DefaultComboBoxModel<>(opcoesDificuldade));
        BotaoComecar.addActionListener(e -> iniciarNovoJogo());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameCampoMinado = new javax.swing.JFrame();
        PainelInformacoes = new javax.swing.JPanel();
        DisplayBandeiras = new javax.swing.JTextField();
        PainelCasas = new javax.swing.JPanel();
        DialogoFimJogo = new javax.swing.JDialog();
        LabelFimJogo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MensagemFimJogo = new javax.swing.JTextPane();
        BotaoOkFimJogo = new javax.swing.JToggleButton();
        ComboBoxDificuldade = new javax.swing.JComboBox<>();
        BotaoComecar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        FrameCampoMinado.setTitle("Campo Minado");
        FrameCampoMinado.setMinimumSize(new java.awt.Dimension(10, 10));

        PainelInformacoes.setBackground(java.awt.SystemColor.control);

        DisplayBandeiras.setEditable(false);
        DisplayBandeiras.setText("Bandeiras Restantes: ");
        DisplayBandeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBandeirasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInformacoesLayout = new javax.swing.GroupLayout(PainelInformacoes);
        PainelInformacoes.setLayout(PainelInformacoesLayout);
        PainelInformacoesLayout.setHorizontalGroup(
            PainelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayBandeiras)
                .addContainerGap())
        );
        PainelInformacoesLayout.setVerticalGroup(
            PainelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayBandeiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelCasas.setBackground(java.awt.SystemColor.control);
        PainelCasas.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout FrameCampoMinadoLayout = new javax.swing.GroupLayout(FrameCampoMinado.getContentPane());
        FrameCampoMinado.getContentPane().setLayout(FrameCampoMinadoLayout);
        FrameCampoMinadoLayout.setHorizontalGroup(
            FrameCampoMinadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCasas, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addComponent(PainelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameCampoMinadoLayout.setVerticalGroup(
            FrameCampoMinadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCampoMinadoLayout.createSequentialGroup()
                .addComponent(PainelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabelFimJogo.setText("Parabens!");

        MensagemFimJogo.setEditable(false);
        MensagemFimJogo.setText("Voce encontrou todas as bombas!");
        MensagemFimJogo.setFocusCycleRoot(false);
        MensagemFimJogo.setFocusable(false);
        jScrollPane3.setViewportView(MensagemFimJogo);

        BotaoOkFimJogo.setText("Ok");
        BotaoOkFimJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkFimJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogoFimJogoLayout = new javax.swing.GroupLayout(DialogoFimJogo.getContentPane());
        DialogoFimJogo.getContentPane().setLayout(DialogoFimJogoLayout);
        DialogoFimJogoLayout.setHorizontalGroup(
            DialogoFimJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoFimJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogoFimJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(DialogoFimJogoLayout.createSequentialGroup()
                        .addComponent(LabelFimJogo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BotaoOkFimJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        DialogoFimJogoLayout.setVerticalGroup(
            DialogoFimJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoFimJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFimJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoOkFimJogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo Minado - Maria Fernanda Zandona");

        ComboBoxDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDificuldadeActionPerformed(evt);
            }
        });

        BotaoComecar.setText("Jogar");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Trabalho de campo minado\nfeito por Maria Fernanda Zandona Casagrande \nClique esquerdo = colocar bandeira (F) \nClique direito = abrir casa ");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setDisabledTextColor(javax.swing.UIManager.getDefaults().getColor("TextField.light"));
        jTextArea1.setEnabled(false);
        jTextArea1.setFocusable(false);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoComecar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayBandeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBandeirasActionPerformed
    }//GEN-LAST:event_DisplayBandeirasActionPerformed

    private void ComboBoxDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDificuldadeActionPerformed
    }//GEN-LAST:event_ComboBoxDificuldadeActionPerformed

    private void BotaoOkFimJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkFimJogoActionPerformed
        fecharDialogoFimJogo(FrameCampoMinado);
    }//GEN-LAST:event_BotaoOkFimJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuInicial().setVisible(true));
    }
    
    public JDialog getDialogoFimJogo() {
        return this.DialogoFimJogo;
    }
    
    public JLabel getLabelFimJogo() {
        return this.LabelFimJogo;
    } 
    
    public JTextPane getMensagemFimJogo() {
        return this.MensagemFimJogo;
    } 
    
    public JTextField getDisplayBandeiras() {
        return this.DisplayBandeiras;
    }

    public void iniciarNovoJogo() {
        this.setVisible(false);
        CampoMinado campoMinado;
        PainelCasas.removeAll();
        switch (this.ComboBoxDificuldade.getSelectedIndex()) {
            case 1 -> {
                campoMinado = new CampoMinado(16, 16, 40);
                PainelCasas.setLayout(new GridLayout(16, 16));
            }
            case 2 -> {
                campoMinado = new CampoMinado(30, 16, 99);
                PainelCasas.setLayout(new GridLayout(30, 16));
            }
            case 0 -> {
                campoMinado = new CampoMinado(9, 9, 10);
                PainelCasas.setLayout(new GridLayout(9, 9));
            }
            default -> {
                campoMinado = new CampoMinado(9, 9, 10);
                PainelCasas.setLayout(new GridLayout(9, 9));
            }
        }
        
        CampoMinadoController controller = new CampoMinadoController(campoMinado, this);
        campoMinado.setListener(controller);
        campoMinado.gerarJogo();
        for (Casa c : campoMinado.getCasas()) {
            PainelCasas.add(c);
        }
        
        controller.onFlagChange();
        FrameCampoMinado.setVisible(true);
        FrameCampoMinado.pack();
        
        
    }
    
    public void fecharDialogoFimJogo(JFrame frameCampoMinado) {
        frameCampoMinado.setVisible(false);
        DialogoFimJogo.setVisible(false);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoComecar;
    private javax.swing.JToggleButton BotaoOkFimJogo;
    private javax.swing.JComboBox<String> ComboBoxDificuldade;
    private javax.swing.JDialog DialogoFimJogo;
    private javax.swing.JTextField DisplayBandeiras;
    private javax.swing.JFrame FrameCampoMinado;
    private javax.swing.JLabel LabelFimJogo;
    public javax.swing.JTextPane MensagemFimJogo;
    private javax.swing.JPanel PainelCasas;
    private javax.swing.JPanel PainelInformacoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
