/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.mafer.campominado;

import java.awt.GridLayout;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author fefe
 */
public class MenuInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicial.class.getName());

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        String[] opcoesDificuldade = {"Fácil: 9x9, 10 minas ", "Médio: 16x16, 40 minas", "Avançado: 30x16, 99 minas"};
        ComboBoxDificuldade.setModel(new DefaultComboBoxModel<>(opcoesDificuldade));
        BotaoComecar.addActionListener(e -> {
            CampoMinado campoMinado;
            switch (ComboBoxDificuldade.getSelectedIndex()) {
                case 1 -> {
                    campoMinado = new CampoMinado(16, 16, 40);
                    PainelCasas.setLayout(new GridLayout(16, 16));
                }
                case 2 -> {
                    campoMinado = new CampoMinado(30, 16, 99);
                    PainelCasas.setLayout(new GridLayout(30, 16));
                }
                case 0 -> {
                    campoMinado = new CampoMinado(9, 9, 10);
                    PainelCasas.setLayout(new GridLayout(9, 9));
                }
                default -> {
                    campoMinado = new CampoMinado(9, 9, 10);
                    PainelCasas.setLayout(new GridLayout(9, 9));
                }
            }
            PainelCasas.removeAll();
            campoMinado.gerarJogo();
            for (Casa c : campoMinado.getCasas()) {
                PainelCasas.add(c);
            }
            
            FrameCampoMinado.setVisible(true);
            FrameCampoMinado.pack();
        });
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameCampoMinado = new javax.swing.JFrame();
        PainelInformacoes = new javax.swing.JPanel();
        DisplayBandeiras = new javax.swing.JTextField();
        PainelCasas = new javax.swing.JPanel();
        ComboBoxDificuldade = new javax.swing.JComboBox<>();
        BotaoComecar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        FrameCampoMinado.setTitle("Campo Minado");
        FrameCampoMinado.setMaximumSize(new java.awt.Dimension(1000, 1000));
        FrameCampoMinado.setMinimumSize(new java.awt.Dimension(10, 10));

        PainelInformacoes.setBackground(java.awt.SystemColor.control);

        DisplayBandeiras.setEditable(false);
        DisplayBandeiras.setText("Bandeiras Restantes: ");
        DisplayBandeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBandeirasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelInformacoesLayout = new javax.swing.GroupLayout(PainelInformacoes);
        PainelInformacoes.setLayout(PainelInformacoesLayout);
        PainelInformacoesLayout.setHorizontalGroup(
            PainelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayBandeiras)
                .addContainerGap())
        );
        PainelInformacoesLayout.setVerticalGroup(
            PainelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayBandeiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelCasas.setBackground(java.awt.SystemColor.control);
        PainelCasas.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout FrameCampoMinadoLayout = new javax.swing.GroupLayout(FrameCampoMinado.getContentPane());
        FrameCampoMinado.getContentPane().setLayout(FrameCampoMinadoLayout);
        FrameCampoMinadoLayout.setHorizontalGroup(
            FrameCampoMinadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCasas, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addComponent(PainelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameCampoMinadoLayout.setVerticalGroup(
            FrameCampoMinadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCampoMinadoLayout.createSequentialGroup()
                .addComponent(PainelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo Minado - Maria Fernanda Zandona");

        ComboBoxDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotaoComecar.setText("Jogar");

        jTextPane1.setEditable(false);
        jTextPane1.setText("Trabalho de campo minado feito por Maria Fernanda Zandona Casagrande Clique esquerdo = colocar bandeira (F) Clique direito = abrir casa ");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoComecar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayBandeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBandeirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayBandeirasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoComecar;
    private javax.swing.JComboBox<String> ComboBoxDificuldade;
    private javax.swing.JTextField DisplayBandeiras;
    private javax.swing.JFrame FrameCampoMinado;
    private javax.swing.JPanel PainelCasas;
    private javax.swing.JPanel PainelInformacoes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
